package generics.watercolors;

public enum Watercolors {
	ZINC,LEMON_YELLOW,MEDIUM_YELLOW,DEEP_YELLOW,OGANGE,BRILLIANT_RED,
	CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,CERULEAN_BLUE_HUE,PHTHALO_BLUE,
	ULTRAMARINE,COBALT_BLUE_HUE,PERMANENT_GREEN,VIRIDIAN_HUE,SAP_GREEN,YELLOW_OCHRE,
	BURNT_SIENNA,RAW_WMBER,BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK;
}
